# general settings
name: 2_styleclip_16image
# 00155_Surprised
# 00065_Curly_Hair
# 00170_Awomanwithabeard

gpus: [0]
seed: 310

scale: 16
# in_size: 8
# out_size: 1024

epochs: 2
limit_train_batches: 1.0
val_check_interval: 500
precision: 32
num_sanity_val_steps: 2
log_every_n_steps: 100

tb_log_img_every_n_steps_train: 500
tb_log_img_every_n_steps_val: 500

# dataset and data loader settings
# CelebAMask-HQ
# |---CelebA-HQ-img-16down
# |---CelebA-caption

data:
  root_path: /root/nas_dataset/CelebAHQ
  caption_path: /root/nas_dataset/CelebAHQ/celeba-caption_mw
  num_workers: 1

  train:
    name: ClipGpenIter
    scale: 16
    gt_size: 256
    use_hflip: true
    use_rot: false

    # data loader
    use_shuffle: true
    batch_size_per_gpu: 1
    # batch_size: 4
    pin_memory: true
    repeat: 5000

    image_id: "00009"
    caption: "Happy"

  val:
    name: CelebAHQ

  test:
    name: ClipGpenIter
    scale: 16
    gt_size: 256
    use_hflip: false
    use_rot: false

    # data loader
    use_shuffle: true
    
    batch_size: 1
    pin_memory: true

    image_id: "00009"
    caption: "Happy"

# network structures
network:
  type: clipgpen

  batch_size: 1 #4
  freeze_d_epoch: 0
  log_images: true

  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingLR
    T_max: 30
    eta_min: !!float 1e-7
  
  # TODO give pretrained option to generator
  # Generator configs
  generator:
    in_size: 16
    out_size: 256
    pretrained:  
      ckpt_path: /root/nas_dajinhan/models/GPEN/GPEN-BFR-256.pth
  
  # Discriminator configs
  discriminator:
    type: StyleGANv2Discriminator
    args:
      in_size: 256
      pretrained: 
        ckpt_path: https://download.openmmlab.com/mmgen/stylegan2/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth 
        prefix: discriminator

  loss:
    
    clip_weight: 1.0

    lr_cons_weight: 0 #2.0 
    image_l2_weight: 0.8
    caption_l2_weight: 0.8
    id_weight: 0.01
    id_pretrained_path: /root/nas_dajinhan/models/CLIPGLEAN/model_ir_se50.pth
    
    perceptual_weight: 0 #0.001
    style_weight: 0 #0.001

    gan_weight: 0 # 0.01
        
  ckpt_path: ~


# TODO implement configs for logger
logger:
